# Generated by Django 4.2.2 on 2023-06-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pirateDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PirateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('pirate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pirateDatabase.pirate')),
            ],
        ),
    ]
